<?php
return [
    'Warning'                                                                                               => '温馨提示',
    'Installing FastAdmin'                                                                                  => '安装FastAdmin',
    'Mysql Hostname'                                                                                        => 'MySQL 数据库地址',
    'Mysql Database'                                                                                        => 'MySQL 数据库名',
    'Mysql Username'                                                                                        => 'MySQL 用户名',
    'Mysql Password'                                                                                        => 'MySQL 密码',
    'Mysql Prefix'                                                                                          => 'MySQL 数据表前缀',
    'Mysql Hostport'                                                                                        => 'MySQL 端口号',
    'Admin Username'                                                                                        => '管理员用户名',
    'Admin Email'                                                                                           => '管理员Email',
    'Admin Password'                                                                                        => '管理员密码',
    'Repeat Password'                                                                                       => '重复管理员密码',
    'Website'                                                                                               => '网站名称',
    'My Website'                                                                                            => '我的网站',
    'Install now'                                                                                           => '点击安装',
    'Installing'                                                                                            => '安装中...',
    'Home'                                                                                                  => '访问首页',
    'Dashboard'                                                                                             => '进入后台',
    'Go back'                                                                                               => '返回上一页',
    'Install Successed'                                                                                     => '安装成功！',
    'Security tips'                                                                                         => '温馨提示：请将以下后台登录入口添加到你的收藏夹，为了你的安全，不要泄漏或发送给他人！如有泄漏请及时修改！',
    'Please input correct database'                                                                         => '请输入正确的数据库名',
    'Please input correct username'                                                                         => '用户名只能由3-30位数字、字母、下划线组合',
    'Please input correct password'                                                                         => '密码长度必须在6-30位之间，不能包含空格',
    'Password is too weak'                                                                                  => '密码太简单，请重新输入',
    'The two passwords you entered did not match'                                                           => '两次输入的密码不一致',
    'Please input correct website'                                                                          => '网站名称输入不正确',
    'The current version %s is too low, please use PHP 7.1 or higher'                                       => '当前版本%s过低，请使用PHP7.1以上版本',
    'PDO is not currently installed and cannot be installed'                                                => '当前未开启PDO，无法进行安装',
    'The current permissions are insufficient to write the file %s'                                         => '当前权限不足，无法写入文件%s',
    'Please go to the official website to download the full package or resource package and try to install' => '当前代码仅包含核心代码，请前往官网下载完整包或资源包覆盖后再尝试安装',
    'The system has been installed. If you need to reinstall, please remove %s first'                       => '当前已经安装成功，如果需要重新安装，请手动移除%s文件',
];
