<form id="edit-form" class="form-horizontal form-ajax" role="form" data-toggle="validator" method="POST" action="">

    <div class="form-group">
        <label for="c-partner_id" class="control-label col-xs-12 col-sm-2">{:__('Partner_id')}:</label>
        <div class="col-xs-12 col-sm-8">
            <input type="text" name="row[partner_id]" value="{$row.partner_id}"  id="c-partner_id" class="form-control "required />
        </div>
    </div>
    <div class="form-group">
        <label for="c-role_id" class="control-label col-xs-12 col-sm-2">{:__('Role_id')}:</label>
        <div class="col-xs-12 col-sm-8">
            <input type="text" name="row[role_id]" value="{$row.role_id}"  id="c-role_id" class="form-control " />
        </div>
    </div>
    <div class="form-group">
        <label for="c-area_id" class="control-label col-xs-12 col-sm-2">{:__('Area_id')}:</label>
        <div class="col-xs-12 col-sm-8">
            <input type="text" name="row[area_id]" value="{$row.area_id}"  id="c-area_id" class="form-control " />
        </div>
    </div>
    <div class="form-group">
        <label for="c-editor_id" class="control-label col-xs-12 col-sm-2">{:__('Editor_id')}:</label>
        <div class="col-xs-12 col-sm-8">
            <input type="text" name="row[editor_id]" value="{$row.editor_id}"  id="c-editor_id" class="form-control " />
        </div>
    </div>
    <div class="form-group">
        <label for="c-editor_id" class="control-label col-xs-12 col-sm-2">{:__('Wx_id')}:</label>
        <div class="col-xs-12 col-sm-8">
            <input type="text" name="row[wx_id]" value="{$row.wx_id}"  id="c-wx_id" class="form-control" />
        </div>
    </div>
    <div class="form-group">
        <label for="c-level" class="control-label col-xs-12 col-sm-2">{:__('Level')}:</label>
        <div class="col-xs-12 col-sm-8">
            <input type="number" name="row[level]" value="{$row.level}"  id="c-level" class="form-control  " />
        </div>
    </div>
    <div class="form-group">
        <label for="c-star" class="control-label col-xs-12 col-sm-2">{:__('Star')}:</label>
        <div class="col-xs-12 col-sm-8">
            <input type="number" name="row[star]" value="{$row.star}"  id="c-star" class="form-control  " />
        </div>
    </div>
    <div class="form-group">
        <label for="c-username" class="control-label col-xs-12 col-sm-2">{:__('Username')}:</label>
        <div class="col-xs-12 col-sm-8">
            <input type="text" name="row[username]" value="{$row.username}"  id="c-username" class="form-control" required />
        </div>
    </div>
    <div class="form-group">
        <label for="c-nickname" class="control-label col-xs-12 col-sm-2">{:__('Nickname')}:</label>
        <div class="col-xs-12 col-sm-8">
            <input type="text" name="row[nickname]" value="{$row.nickname}"  id="c-nickname" class="form-control" required />
        </div>
    </div>
    <div class="form-group">
        <label for="c-password" class="control-label col-xs-12 col-sm-2">{:__('Password')}:</label>
        <div class="col-xs-12 col-sm-8">
            <input type="text" name="row[password]" value="{$row.password}"  id="c-password" class="form-control" required />
        </div>
    </div>
    <div class="form-group">
        <label for="c-salt" class="control-label col-xs-12 col-sm-2">{:__('Salt')}:</label>
        <div class="col-xs-12 col-sm-8">
            <input type="text" name="row[salt]" value="{$row.salt}"  id="c-salt" class="form-control" required />
        </div>
    </div>
    <div class="form-group">
        <label for="c-email" class="control-label col-xs-12 col-sm-2">{:__('Email')}:</label>
        <div class="col-xs-12 col-sm-8">
            <input type="text" name="row[email]" value="{$row.email}"  id="c-email" class="form-control" />
        </div>
    </div>
    <div class="form-group">
        <label for="c-mobile" class="control-label col-xs-12 col-sm-2">{:__('Mobile')}:</label>
        <div class="col-xs-12 col-sm-8">
            <input type="text" name="row[mobile]" value="{$row.mobile}"  id="c-mobile" class="form-control" />
        </div>
    </div>
    <div class="form-group">
        <label for="c-avatar" class="control-label col-xs-12 col-sm-2">{:__('Avatar')}:</label>
        <div class="col-xs-12 col-sm-8">
            <div class="form-inline">
                <input type="text" name="row[avatar]" value="{$row.avatar}"  id="c-avatar" class="form-control" required size="50" />
                <span><button id="plupload-avatar" class="btn btn-danger plupload" data-input-id="c-avatar"><i class="fa fa-upload"></i> {:__("Upload")}</button></span>
            </div>
        </div>
    </div>
    <div class="form-group">
        <label for="c-gender" class="control-label col-xs-12 col-sm-2">{:__('Gender')}:</label>
        <div class="col-xs-12 col-sm-8">
            <input type="number" name="row[gender]" value="{$row.gender}"  id="c-gender" class="form-control  " />
        </div>
    </div>
    <div class="form-group">
        <label for="c-birthday" class="control-label col-xs-12 col-sm-2">{:__('Birthday')}:</label>
        <div class="col-xs-12 col-sm-8">
            <input type="text" name="row[birthday]" value="{$row.birthday}"  id="c-birthday" class="form-control" required />
        </div>
    </div>
    <div class="form-group">
        <label for="c-score" class="control-label col-xs-12 col-sm-2">{:__('Score')}:</label>
        <div class="col-xs-12 col-sm-8">
            <input type="number" name="row[score]" value="{$row.score}"  id="c-score" class="form-control  " />
        </div>
    </div>
    <div class="form-group">
        <label for="c-feeds" class="control-label col-xs-12 col-sm-2">{:__('Feeds')}:</label>
        <div class="col-xs-12 col-sm-8">
            <input type="number" name="row[feeds]" value="{$row.feeds}"  id="c-feeds" class="form-control  " />
        </div>
    </div>
    <div class="form-group">
        <label for="c-follows" class="control-label col-xs-12 col-sm-2">{:__('Follows')}:</label>
        <div class="col-xs-12 col-sm-8">
            <input type="number" name="row[follows]" value="{$row.follows}"  id="c-follows" class="form-control  " />
        </div>
    </div>
    <div class="form-group">
        <label for="c-fans" class="control-label col-xs-12 col-sm-2">{:__('Fans')}:</label>
        <div class="col-xs-12 col-sm-8">
            <input type="number" name="row[fans]" value="{$row.fans}"  id="c-fans" class="form-control  " />
        </div>
    </div>
    <div class="form-group">
        <label for="c-loginfailure" class="control-label col-xs-12 col-sm-2">{:__('Loginfailure')}:</label>
        <div class="col-xs-12 col-sm-8">
            <input type="number" name="row[loginfailure]" value="{$row.loginfailure}"  id="c-loginfailure" class="form-control  " />
        </div>
    </div>
    <div class="form-group">
        <label for="c-logintime" class="control-label col-xs-12 col-sm-2">{:__('Logintime')}:</label>
        <div class="col-xs-12 col-sm-8">
            <input type="datetime" name="row[logintime]" value="{$row.logintime|datetime}"  id="c-logintime" class="form-control datetimepicker   " />
        </div>
    </div>
    <div class="form-group">
        <label for="c-loginip" class="control-label col-xs-12 col-sm-2">{:__('Loginip')}:</label>
        <div class="col-xs-12 col-sm-8">
            <input type="text" name="row[loginip]" value="{$row.loginip}"  id="c-loginip" class="form-control" required />
        </div>
    </div>
    <div class="form-group">
        <label for="c-joinip" class="control-label col-xs-12 col-sm-2">{:__('Joinip')}:</label>
        <div class="col-xs-12 col-sm-8">
            <input type="text" name="row[joinip]" value="{$row.joinip}"  id="c-joinip" class="form-control" required />
        </div>
    </div>
    <div class="form-group">
        <label for="c-jointime" class="control-label col-xs-12 col-sm-2">{:__('Jointime')}:</label>
        <div class="col-xs-12 col-sm-8">
            <input type="datetime" name="row[jointime]" value="{$row.jointime|datetime}"  id="c-jointime" class="form-control datetimepicker   " />
        </div>
    </div>
    <div class="form-group">
        <label for="c-address" class="control-label col-xs-12 col-sm-2">{:__('Address')}:</label>
        <div class="col-xs-12 col-sm-8">
            <input type="text" name="row[address]" value="{$row.address}"  id="c-address" class="form-control" />
        </div>
    </div>
    <div class="form-group">
        <label for="c-receiver" class="control-label col-xs-12 col-sm-2">{:__('Receiver')}:</label>
        <div class="col-xs-12 col-sm-8">
            <input type="text" name="row[receiver]" value="{$row.receiver}"  id="c-receiver" class="form-control" />
        </div>
    </div>
    <div class="form-group">
        <label for="c-token" class="control-label col-xs-12 col-sm-2">{:__('Token')}:</label>
        <div class="col-xs-12 col-sm-8">
            <input type="text" name="row[token]" value="{$row.token}"  id="c-token" class="form-control" required />
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-xs-12 col-sm-2">{:__('Status')}:</label>
        <div class="col-xs-12 col-sm-8">
            {:build_radios('row[status]', ['normal'=>__('Normal'), 'hidden'=>__('Hidden')], $row['status'])}
        </div>
    </div>
    <div class="form-group hide layer-footer">
        <label class="control-label col-xs-12 col-sm-2"></label>
        <div class="col-xs-12 col-sm-8">
            <button type="submit" class="btn btn-success btn-embossed disabled">{:__('OK')}</button>
            <button type="reset" class="btn btn-default btn-embossed">{:__('Reset')}</button>
        </div>
    </div>
</form>
